#!/usr/bin/python

generatePlots = True
numRuns = 1

import sys
from random import randint
if (generatePlots):
	import matplotlib.pyplot as plt

class Node:
	def __init__(self, ID=-1, maxAttempts=0):
		self.ID = ID
		self.maxAttempts = maxAttempts
		self.backoff = -1
		self.currRange = 0
		self.tryCount = 0
		self.ranges = []
		self.numDropped = 0
		self.totalCollision = 0
		self.numSent = 0
	def setBackoff(self):
		self.backoff = randint(0,self.currRange)
	def countDown(self):
		self.backoff = self.backoff-1;
	def setRange(self, newRange):
		self.currRange = newRange
	def setRanges(self,ranges):
		self.ranges = ranges
	def getRange(self,index):
		if(len(self.ranges)==0):
			return 2**index
		if(index>=len(self.ranges)):
			return self.ranges[-1]*(2**(index-len(self.ranges)))
		else:
			return self.ranges[index]
	def setRangeAndBackoff(self):
		self.setRange(self.getRange(self.tryCount))
		self.setBackoff()
	def collision(self):
		self.tryCount = self.tryCount+1
		self.totalCollision+=1
		if(self.tryCount>=self.maxAttempts):
			self.tryCount=0
			self.numDropped = self.numDropped+1
			self.setRangeAndBackoff()
		else:
			self.setRangeAndBackoff()

class Channel:
	def __init__ (self, args):
		(N,L,R,M,T) = args
		self.numNodes = N
		self.packetSize = L
		self.ranges = R # a list
		self.maxAttempts = M
		self.simTime = T
		self.channelOccupied = 0
		self.occupiedTime = 0
		self.occupiedCount = 0
		self.idleCount = 0
		self.nodes = []
		self.collisions = 0
		self.successPackets = 0
		self.totalLocalSent = 0
		self.avgLocalSent = 0.0
		self.totalLocalCollisions = 0
		self.avgLocalCollisions = 0.0
		self.varianceSent = 0.0
		self.varianceCollisions = 0.0
		for i in range(self.numNodes):
			self.nodes.append(Node(i+1, self.maxAttempts))
	def occupyChannel(self, nodeID):
		self.channelOccupied = nodeID
	def freeChannel(self):
		self.channelOccupied = 0
	def getOccupiedPct(self):
		return (float(self.occupiedCount)/float((self.occupiedCount + self.idleCount)))*100.0
	def getIdlePct(self):
		return (float(self.idleCount)/float((self.occupiedCount + self.idleCount)))*100.0
	def getAvgST(self):
		for node in self.nodes:
			self.totalLocalSent += node.numSent
		self.avgLocalSent = float(self.totalLocalSent)/float(len(self.nodes))
	def getVarST(self):
		totalVariance = 0.0
		for node in self.nodes:
			totalVariance += float(self.avgLocalSent-node.numSent)**2.0
		self.varianceSent = float(totalVariance)/float(len(self.nodes))
	def getAvgLocalCollisions(self):
		for node in self.nodes:
			self.totalLocalCollisions += node.totalCollision
		self.avgLocalCollisions = float(self.totalLocalCollisions)/float(len(self.nodes))
	def getVarCollisions(self):
		totalVariance = 0.0
		for node in self.nodes:
			totalVariance += float(self.avgLocalCollisions-node.totalCollision)**2.0
		self.varianceCollisions = float(totalVariance)/float(len(self.nodes))
	def initNodes(self):
		for node in self.nodes:
			node.setRanges(self.ranges)
			node.setRangeAndBackoff()
	def tick(self):
		self.occupiedTime = max(0,self.occupiedTime - 1)
		if(self.occupiedTime == 0): # open channel case
			if(self.channelOccupied!=0):
				self.nodes[self.channelOccupied-1].tryCount=0
				self.nodes[self.channelOccupied-1].setRangeAndBackoff()
				self.successPackets = self.successPackets+1
				self.nodes[self.channelOccupied-1].numSent = self.nodes[self.channelOccupied-1].numSent + 1
				self.channelOccupied = 0
			zerolist = []
			for node in self.nodes:
				#print str(node.ID) + ": " + str(node.backoff)
				if(node.backoff==0):
					zerolist.append(node)
			if(len(zerolist) == 1): # claim the channel case
				self.channelOccupied = zerolist[0].ID
				self.occupiedTime = self.packetSize
				self.occupiedCount+=1
			elif(len(zerolist) > 1): # collisions case
				self.collisions += 1#len(zerolist) - 1
				for i in range(len(zerolist)):
					zerolist[i].collision()
				self.occupiedCount += 1
			else:
				for node in self.nodes:
					node.countDown()
				self.idleCount += 1
		else: # occupied channel case
			self.occupiedCount = self.occupiedCount + 1
	def printResults(self):
		self.getAvgST()
		self.getAvgLocalCollisions()
		self.getVarST()
		self.getVarCollisions()
		print "Channel Utilization percentage: " + str(self.getOccupiedPct())
		print "Channel Idle percentage: " + str(self.getIdlePct())
		print "Total number of collision: " + str(self.collisions)
		print "Variance in number of successful transmissions: " + str(self.varianceSent)
		print "Variance in number of local collisions: " + str(self.varianceCollisions)
	def getResults(self):
		self.getAvgST()
		self.getAvgLocalCollisions()
		self.getVarST()
		self.getVarCollisions()
		results = ""
		results += (str(self.getOccupiedPct()) + str("\n"))
		results += (str(self.getIdlePct()) + str("\n"))
		results += (str(self.collisions) + str("\n"))
		results += (str(self.varianceSent) + str("\n"))
		results += (str(self.varianceCollisions) + str("\n"))
		return results
	def getResultsNums(self):
                self.getAvgST()
                self.getAvgLocalCollisions()
                self.getVarST()
                self.getVarCollisions()
                results = []
                results.append(self.getOccupiedPct())
                results.append(self.getIdlePct())
                results.append(self.collisions)
                results.append(self.varianceSent)
                results.append(self.varianceCollisions)
                return results

def parse(filename):
	f = open(filename, "r")
	lines = f.readlines()
	numNodes = 0
	packetSize = 0
	ranges = []
	maxAttempts = 0
	simTime = 0
	for line in lines:
		#grab initialization vars
		curr = line.split(" ")
		if(curr[0] == "N"):
			# print "numNodes: " + curr[1]
			numNodes = int(curr[1])	
		elif(curr[0] == "L"):
			# print "packetSize: " + curr[1]
			packetSize = int(curr[1])
		elif(curr[0] == "R"):
			for i in xrange(1, len(curr), 1):
				# print "range: " + curr[i]
				ranges.append(int(curr[i]))
		elif(curr[0] == "M"):
			# print "maxAttempts: " + curr[1]
			maxAttempts = int(curr[1])
		elif(curr[0] == "T"):
			# print "simTime: " + curr[1]
			simTime = int(curr[1].replace(',', ''))
		else:
			print "Error: Invalid input file"
	# print "numNodes: " + str(numNodes)
	# print "packetSize: " + str(packetSize)
	# print "ranges: " +  '[%s]' % ', '.join(map(str, ranges))
	# print "simTime: " + str(simTime)
	result = []
	result.append(numNodes)
	result.append(packetSize)
	result.append(ranges)
	result.append(maxAttempts)
	result.append(simTime)
	f.close()
	return result

def main(argc, argv):
	args = parse(argv[1])
	# for arg in args:
	# 	 print str(arg)
	channel = Channel(args)

	channel.initNodes()
	for simulation in xrange(0, channel.simTime):
		channel.tick()
		#channel.printResults()
		#raw_input()
	# channel.printResults()

	f = open("output.txt", "w")
	f.write(channel.getResults())
	f.close()

	if(generatePlots):
		
		args = []
		args.append(25)
		args.append(20)
		ranges = [8, 16, 32, 64, 128]
		args.append(ranges)
		args.append(6)
		args.append(50000)
		
		# parts a-c
		nArray = []
		utilPcts = []
		idlePcts = []
		collisions = []
		for n in xrange(5, 101, 1):
			nArray.append(n)
			args[0] = n
			channel = Channel(args)
			channel.initNodes()
			totalAfterRunsUtil = 0
			totalAfterRunsIdle = 0
			totalAfterRunsCollisions = 0
			for i in xrange(numRuns):
				for simulation in xrange(0, channel.simTime):
					channel.tick()
				totalAfterRunsUtil += (channel.getResultsNums())[0]
				totalAfterRunsIdle += (channel.getResultsNums())[1]
				totalAfterRunsCollisions += (channel.getResultsNums())[2]
			utilPcts.append(float(totalAfterRunsUtil)/float(numRuns))
			idlePcts.append(float(totalAfterRunsIdle)/float(numRuns))
			collisions.append(totalAfterRunsCollisions)
			print "N: " + str(n) + "\tChannel Utilization: " + str(utilPcts[-1]) + " %\t" + " Idle: " + str(idlePcts[-1]) + " %\t" + "Collisions: " + str(collisions[-1])
		# part a
		plt.figure()
		plt.plot(nArray, utilPcts)
		plt.ylabel('Channel Utilization (in percentage)')
		plt.xlabel('N = Number of Nodes (5 to 100)')
		plt.savefig('parta.png')
		plt.ioff()
		plt.close()

		# part b
		plt.figure()
		plt.plot(nArray, idlePcts)
		plt.ylabel('Idle Fraction (in percentage)')
		plt.xlabel('N = Number of Nodes (5 to 100)')
		plt.savefig('partb.png')
		plt.ioff()
		plt.close()

		# part c
		plt.figure()
		plt.plot(nArray, collisions)
		plt.ylabel('Total Number of Collisions')
		plt.xlabel('N = Number of Nodes (5 to 100)')
		plt.savefig('partc.png')
		plt.ioff()
		plt.close()

		# part d
		rangesD = [1, 2, 4, 8, 16]
		fig = plt.figure()
		ax = plt.subplot(111)
		for rangeD in rangesD:
			args[2] = [rangeD]
			nArray = []
			utilPcts = []
			for n in xrange(5, 101, 1):
				nArray.append(n)
				args[0] = n
				channel = Channel(args)
				channel.initNodes()
				totalAfterRunsUtil = 0
				for i in xrange(numRuns):
					for simulation in xrange(0, channel.simTime):
						channel.tick()
					totalAfterRunsUtil += (channel.getResultsNums())[0]
				utilPcts.append(float(totalAfterRunsUtil)/float(numRuns))
				print "R: " + str(rangeD) + "\tN: " + str(n) + "\tChannel Utilization: " + str(utilPcts[-1]) + "%"
			plt.plot(nArray, utilPcts, label = "R=" + str(rangeD))
		box = ax.get_position()
		ax.set_position([box.x0, box.y0 + box.height * 0.15, box.width, box.height * 0.85])
		ax.legend(loc='upper center', bbox_to_anchor=(.5, -0.10), fancybox=True, shadow=True, ncol=len(rangesD))
		plt.ylabel('Channel Utilization (in percentage)')
		plt.xlabel('N = Number of Nodes (5 to 100)')
		# plt.legend()
		plt.savefig('partd.png')
		plt.ioff()
		plt.close()

		# part e
		args[2] = [8, 16, 32, 64, 128]
		lValues = [20, 40, 60, 80, 100]
		plt.figure()
		for lval in lValues:
			args[1] = lval
			nArray = []
			utilPcts = []
			for n in xrange(5, 101, 1):
				nArray.append(n)
				args[0] = n
				channel = Channel(args)
				channel.initNodes()
				totalAfterRunsUtil = 0
				for i in xrange(numRuns):
					for simulation in xrange(0, channel.simTime):
						channel.tick()
					totalAfterRunsUtil += (channel.getResultsNums())[0]
				utilPcts.append(float(totalAfterRunsUtil)/float(numRuns))
				print "L: " + str(lval) + "\tN: " + str(n) + "\tChannel Utilization: " + str(utilPcts[-1]) + "%"
			plt.plot(nArray, utilPcts, label = "L=" + str(lval))
 
                plt.ylabel('Channel Utilization (in percentage)')
                plt.xlabel('N = Number of Nodes (5 to 100)')
                plt.legend()
                plt.savefig('parte.png')
                plt.ioff()
                plt.close()


if __name__ == '__main__':
	main(len(sys.argv), sys.argv);

